- name: Repair accountanting service (Nginx Restart)
  hosts: localhost
  connection: local
  tasks:
    - name: Restart Nginx service (Docker Container)
      community.docker.docker_container:
        name: bank_api_gateway
        state: started
        restart: yes
      register: result

    - name: Print result
      debug:
        msg: "Successuly restarted accountanting API Gateway service."